### ISSUE TITLE
Will SFZero support keyswitches?

### ISSUE THREAD

**Issue by jamshark70** [stevefolta/SFZero#7]
I just attempted to test keyswitches, and none of the selector keys have any effect.

So I have to assume this hasn't been implemented. Are there any plans to do so?

(The quandary that I'm in is that sfizz ~~doesn't~~ does support switches but doesn't save the instance's state correctly. So that's unusable. SFZero built into Carla does restore its state correctly but is missing features from the instrument.)

**Comment by stevefolta** [comment]
No plans to implement that, sorry.  This is the first I've heard of sfizz, looks promising, hopefully they'll fix that bug.

**Comment by jamshark70** [comment]
Ok, will close this issue.

The state of sample players in Linux is... unfortunate 😆 but if that's where it is, then I have to just go with it for now.

Edit: Btw sfizz developers say I should save the patch into a filesystem that supports symbolic links, which I hadn't done. Just mentioning in case anyone stumbles across this thread.
